project/carpool/urls.py
from django.urls import path

from carpool.views import (
    update_reservation,
    cancel_reservation,
    list_my_rides,
    rides_map,
    rides_delete,
    rides_detail,
    rides_list,
    rides_subscribe,
)
from carpool.views import api as api_views
from carpool.views import backoffice as bo_views
from carpool.views import vehicle as vehicle_views
from carpool.views import rides as rides_views
from chat.views import request_chat

app_name = "carpool"

urlpatterns = [
    path("", rides_list, name="list"),
    path("my-rides/", list_my_rides, name="my-rides"),
    path("<uuid:pk>/", rides_detail, name="detail"),
    path("<uuid:pk>/delete/", rides_delete, name="delete"),
    path("map/", rides_map, name="map"),
    path("<uuid:ride_pk>/chat/", request_chat, name="chat"),
    path("<uuid:ride_pk>/subscribe/", rides_subscribe, name="subscribe"),
]

urlpatterns += [
    path("<uuid:pk>/edit/", rides_views.edit, name="edit"),
    path("create/step1/", rides_views.create_step1, name="create_step1"),
    path("create/step2/", rides_views.create_step2, name="create_step2"),
]


# API endpoints
urlpatterns += [
    path("api/reservations/cancel/", cancel_reservation, name="cancel_reservation"),
    path("api/reservations/update/", update_reservation, name="update_reservation"),
    path("api/vehicles/new/", vehicle_views.create, name="create_vehicle"),
    path("api/vehicles/<int:pk>/update/", vehicle_views.update, name="update_vehicle"),
    path("api/completion/", api_views.autocompletion, name="completion"),
    path("api/routing/", api_views.routing, name="routing"),
]


# Back office specific URLs
urlpatterns += [
    path("back-office/statistics/", bo_views.statistics, name="bo_statistics"),
    path(
        "back-office/statistics/json/",
        bo_views.statistics_json_monthly,
        name="bo_statistics_json_monthly",
    ),
]

project/chat/urls.py
from django.urls import path

from chat.views import (
    hide_message,
    index,
    mod_center,
    mod_room,
    report,
    room,
    unhide_message,
    user_report,
)

app_name = "chat"

urlpatterns = [
    path("", index, name="index"),
    path("<uuid:jr_pk>/", room, name="room"),
    path("<uuid:jr_pk>/report/", report, name="report"),
]

urlpatterns += [
    path("mod/", mod_center, name="mod_index"),
    path("mod/<uuid:jr_pk>/", mod_room, name="mod_room"),
    path("mod/msg/<int:id>/hide/", hide_message, name="hide_message"),
    path("mod/msg/<int:id>/unhide/", unhide_message, name="unhide_message"),
    path("mod/user/<uuid:user_pk>/report/", user_report, name="user_report"),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from .views import set_user_language

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),  # language switching
    path(
        "set_language/", set_user_language, name="set_user_language"
    ),  # custom language switching
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("carpool.urls", namespace="carpool")),
    path("chat/", include("chat.urls", namespace="chat")),
]


urlpatterns += [
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/carpool/forms/vehicle.py
from django import forms
from django.conf import settings
from carpool.models import Vehicle


class VehicleForm(forms.ModelForm):
    seats = forms.IntegerField(
        required=True,
        min_value=1,
        max_value=settings.MAXIMUM_SEATS_IN_VEHICLE,
    )

    class Meta:
        model = Vehicle
        fields = ["name", "description", "seats", "geqCO2_per_km"]

project/carpool/views.py
import datetime
import json
import logging

from asgiref.sync import sync_to_async
from chat.models import ChatRequest
from chat.tasks import send_email_confirmed_ride, send_email_declined_ride
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.gis.db.models.functions import Distance
from django.contrib.gis.geos import GEOSGeometry, Point
from django.contrib.gis.measure import D
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.db.models import Count, ExpressionWrapper, F, IntegerField
from django.db.models.functions import TruncDate
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.utils.timezone import localtime
from django.utils.translation import gettext as _
from django.views.decorators.http import require_http_methods

from carpool.forms import CreateRideForm, EditRideForm, VehicleForm
from carpool.models import Location, Vehicle
from carpool.models.ride import Ride
from carpool.models.statistics import MonthlyStatistics, Statistics
from carpool.tasks import get_autocompletion, get_routing


@permission_required(["carpool.view_statistics"])
def bo_statistics_json_monthly(request):
    # Get labels for the current academic year (from September to August)
    now = timezone.now()
    if now.month >= 9:
        start_year = now.year
    else:
        start_year = now.year - 1
    labels = []
    for month in range(9, 13):
        labels.append(f"{month:02d}-{start_year}")
    for month in range(1, 9):
        labels.append(f"{month:02d}-{start_year + 1}")
    monthly_stats = MonthlyStatistics.objects.filter_by_academic_year(start_year)
    monthly_total_rides = [stat.total_rides for stat in monthly_stats]
    monthly_total_users = [stat.total_users for stat in monthly_stats]
    monthly_total_distance = [stat.total_distance for stat in monthly_stats]
    monthly_total_co2 = [stat.total_co2 for stat in monthly_stats]

    data = {
        "labels": labels,
        "monthly_total_rides": monthly_total_rides,
        "monthly_total_users": monthly_total_users,
        "monthly_total_distance": monthly_total_distance,
        "monthly_total_co2": monthly_total_co2,
    }

    return JsonResponse(data)


@permission_required(["carpool.view_statistics"])
def bo_statistics(request):
    if Statistics.objects.count() == 0:
        # Create the Statistics object if it does not exist
        Statistics.objects.create()

    context = {
        "last_updated_at": Statistics.objects.first().updated_at,
        "total_users": Statistics.objects.first().total_users,
        "total_rides": Statistics.objects.first().total_rides,
        "total_distance": Statistics.objects.first().total_distance,
        "total_co2": Statistics.objects.first().total_co2,
    }

    return render(request, "rides/back-office/statistics.html", context)


@login_required
def vehicles_create(request):
    form = VehicleForm()
    if request.method == "POST":
        form = VehicleForm(request.POST)
        if form.is_valid():
            vehicle = form.save(commit=False)
            vehicle.driver = request.user
            vehicle.save()
            logging.info(f"Vehicle {vehicle.pk} created by user {request.user.pk}")
            return JsonResponse(
                {
                    "status": "OK",
                    "vehicle": {
                        "id": vehicle.pk,
                        "name": vehicle.name,
                        "description": vehicle.description,
                        "seats": vehicle.seats,
                        "geqCO2_per_km": vehicle.geqCO2_per_km,
                    },
                },
                status=201,
            )
        else:
            logging.error(f"Vehicle creation form invalid: {form.errors}")
            return JsonResponse({"status": "NOK", "errors": form.errors}, status=400)
    return JsonResponse(
        {"status": "NOK", "error": "Invalid request method"}, status=400
    )


@login_required
def vehicles_update(request, pk):
    vehicle = get_object_or_404(Vehicle, pk=pk)
    if vehicle.driver != request.user:
        return JsonResponse(
            {"status": "NOK", "error": "You are not the driver of this vehicle"},
            status=403,
        )

    form = VehicleForm(instance=vehicle)
    if request.method == "POST":
        form = VehicleForm(request.POST, instance=vehicle)
        if form.is_valid():
            form.save()
            logging.info(f"Vehicle {vehicle.pk} updated by user {request.user.pk}")
            return JsonResponse(
                {
                    "status": "OK",
                    "vehicle": {
                        "id": vehicle.pk,
                        "name": vehicle.name,
                        "description": vehicle.description,
                        "seats": vehicle.seats,
                        "geqCO2_per_km": vehicle.geqCO2_per_km,
                    },
                },
                status=201,
            )
        return JsonResponse({"status": "NOK", "errors": form.errors}, status=400)

    return JsonResponse(
        {"status": "NOK", "error": "Invalid request method"}, status=400
    )


@login_required
def list_my_rides(request):
    p_rides = Ride.objects.filter(driver=request.user).order_by("start_dt")
    s_rides = ChatRequest.objects.filter(user=request.user).order_by("ride__start_dt")

    s_paginator = Paginator(s_rides, 3)
    p_paginator = Paginator(p_rides, 3)

    s_page_num = request.GET.get("s_page")
    p_page_num = request.GET.get("p_page")

    s_page_obj = s_paginator.get_page(s_page_num)
    p_page_obj = p_paginator.get_page(p_page_num)

    context = {
        "s_page_obj": s_page_obj,
        "p_page_obj": p_page_obj,
    }

    return render(request, "rides/my_rides.html", context)


@login_required
def ride_map(request):
    rides = Ride.objects.filter_upcoming()
    rides_geo = []

    for ride in rides:
        if ride.geometry:
            start_dt_local = localtime(ride.start_dt)
            rides_geo.append(
                {
                    "start": [ride.start_loc.lat, ride.start_loc.lng],
                    "end": [ride.end_loc.lat, ride.end_loc.lng],
                    "geometry": json.loads(
                        ride.geometry.geojson
                    ),  # supposé être une chaîne GeoJSON valide
                    "uuid": str(ride.uuid),
                    "start_name": ride.start_loc.fulltext,
                    "start_lat": ride.start_loc.lat,
                    "start_lon": ride.start_loc.lng,
                    "end_name": ride.end_loc.fulltext,
                    "end_lat": ride.end_loc.lat,
                    "end_lon": ride.end_loc.lng,
                    "start_d": start_dt_local.strftime("%A %d %B %Y"),
                    "start_t": start_dt_local.strftime("%H:%M"),
                    "start_dt": start_dt_local.isoformat(),
                    "price": ride.price,
                    "duration": f"{int(ride.duration.total_seconds() // 3600)}h{int((ride.duration.total_seconds() % 3600) // 60)}",
                }
            )

    context = {"rides_geo": rides_geo}
    return render(request, "rides/map.html", context)


@require_http_methods(["POST"])
def change_jrequest_status(request, jr_pk):
    join_request = get_object_or_404(ChatRequest, pk=jr_pk)

    if request.user != join_request.ride.driver:
        return HttpResponse("You are not the driver of this post", status=403)

    action = request.POST.get("action")
    if action == "accept":
        join_request.status = ChatRequest.Status.ACCEPTED
        # Send an email to the user to notify them that their request has been accepted
        send_email_confirmed_ride.delay(join_request.pk)
        # Add the user to the ride
        join_request.ride.rider.add(join_request.user)

    elif action == "decline":
        join_request.status = ChatRequest.Status.DECLINED
        # Remove the user to the ride if they were added
        if join_request.user in join_request.ride.rider.all():
            join_request.ride.rider.remove(join_request.user)
        # Send an email to the user to notify them that their request has been declined
        send_email_declined_ride.delay(join_request.pk)

    else:
        return HttpResponse("Invalid action", status=400)

    join_request.save()
    return redirect("chat:index")


@login_required
def rides_subscribe(request, pk):
    ride = get_object_or_404(Ride, pk=pk)
    if request.method == "POST":
        if ChatRequest.objects.filter(user=request.user, ride=ride).exists():
            messages.error(request, _("You have already requested to join this ride."))
            return redirect("carpool:detail", pk=ride.pk)

        ride.join_requests.create(user=request.user)
        return redirect("chat:index")
    return redirect("carpool:detail", pk=ride.pk)


@login_required
def rides_detail(request, pk):
    # Check if the user has already booked this ride
    # used to disabled the subscribe button
    chat_request = ChatRequest.objects.filter(user=request.user, ride__pk=pk).first()

    ride = get_object_or_404(Ride, pk=pk)
    context = {
        "ride": ride,
        "geometry": ride.geometry.geojson,
        "chat_request": chat_request,
    }

    return render(request, "rides/detail.html", context)


@login_required
def rides_edit(request, pk):
    ride = get_object_or_404(Ride, pk=pk)
    # Check if user has permission
    if ride.driver != request.user:
        return HttpResponse("You are not the driver of this ride", status=403)

    form = EditRideForm(instance=ride)

    if request.method == "POST":
        form = EditRideForm(request.POST, instance=ride)
        if form.is_valid():
            form.save(ride)

project/carpool/views/api.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from asgiref.sync import sync_to_async
from carpool.tasks import get_autocompletion, get_routing


@login_required
async def autocompletion(request) -> JsonResponse:
    """
    An async API proxy endpoint to get latitude and
    longitude for a given query.
    """
    text = request.GET.get("text", "")
    if not text:
        return JsonResponse({"status": "NOK"}, status=400)

    task = get_autocompletion.delay(text)
    result = await sync_to_async(task.get)(timeout=5)  # blocking I/O offloaded
    return JsonResponse({"status": "OK", "results": result}, safe=False, status=200)


@login_required
async def routing(request) -> JsonResponse:
    """
    An async API proxy endpoint to get routing information.
    """
    start = request.GET.get("start", "")
    end = request.GET.get("end", "")
    intermediates = request.GET.getlist("intermediates", [])
    print(intermediates)

    if not start or not end:
        return JsonResponse({"status": "NOK"}, status=400)
    task = get_routing.delay(start, end, intermediates)
    res = await sync_to_async(task.get)(timeout=5)  # blocking I/O offloaded
    return JsonResponse(res, safe=False)

project/carpool/views/backoffice.py
from django.http import JsonResponse
from django.shortcuts import render
from django.utils import timezone
from django.contrib.auth.decorators import permission_required
from carpool.models.statistics import Statistics, MonthlyStatistics


@permission_required(["carpool.view_statistics"])
def statistics_json_monthly(request):
    # Get labels for the current academic year (from September to August)
    now = timezone.now()
    if now.month >= 9:
        start_year = now.year
    else:
        start_year = now.year - 1
    labels = []
    for month in range(9, 13):
        labels.append(f"{month:02d}-{start_year}")
    for month in range(1, 9):
        labels.append(f"{month:02d}-{start_year + 1}")
    monthly_stats = MonthlyStatistics.objects.filter_by_academic_year(start_year)
    monthly_total_rides = [stat.total_rides for stat in monthly_stats]
    monthly_total_users = [stat.total_users for stat in monthly_stats]
    monthly_total_distance = [stat.total_distance for stat in monthly_stats]
    monthly_total_co2 = [stat.total_co2 for stat in monthly_stats]

    data = {
        "labels": labels,
        "monthly_total_rides": monthly_total_rides,
        "monthly_total_users": monthly_total_users,
        "monthly_total_distance": monthly_total_distance,
        "monthly_total_co2": monthly_total_co2,
    }

    return JsonResponse(data)


@permission_required(["carpool.view_statistics"])
def statistics(request):
    if Statistics.objects.count() == 0:
        # Create the Statistics object if it does not exist
        Statistics.objects.create()

    context = {
        "last_updated_at": Statistics.objects.first().updated_at,
        "total_users": Statistics.objects.first().total_users,
        "total_rides": Statistics.objects.first().total_rides,
        "total_distance": Statistics.objects.first().total_distance,
        "total_co2": Statistics.objects.first().total_co2,
    }

    return render(request, "rides/back-office/statistics.html", context)

project/carpool/templates/rides/back-office/statistics.html
{% extends 'base.html' %}{% load static i18n %}


{% block extrahead %}
<link rel="stylesheet" href="{% static 'vendors/bootstrap-icons/bootstrap-icons.css' %}" />

{% endblock extrahead %}

{% block content %}
<div class="container mt-3">
    <div class="d-flex flex-row justify-content-between align-items-center">
        <h1>{% translate "Statistics" %}</h1>
        <span class="align-self-center text-body-secondary ms-3">{{ last_updated_at|date:"d/m/Y H:i" }}</span>
    </div>
    
    <div class="row">
        <div class="col-xl col-md-6 mb-3">
            <div class="card border border-5 border-primary border-end-0 border-top-0 border-bottom-0 shadow py-2 h-100">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs fw-bold text-primary text-uppercase mb-1">
                                {% translate "Total Rides" %}
                            </div>
                            <div class="h5 mb-0 fw-bold text-body-secondary">{{ total_rides|default:0 }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="bi bi-car-front-fill text-body-tertiary display-5 pe-3"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl col-md-6 mb-3">
            <div class="card border border-5 border-warning border-end-0 border-top-0 border-bottom-0 shadow py-2 h-100">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs fw-bold text-warning text-uppercase mb-1">
                                {% translate "Total users" %}
                            </div>
                            <div class="h5 mb-0 fw-bold text-body-secondary">{{ total_users|default:0 }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="bi bi-signpost-split-fill text-body-tertiary display-5 pe-3"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl col-md-6 mb-3">
            <div class="card border border-5 border-info border-end-0 border-top-0 border-bottom-0 shadow py-2 h-100">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs fw-bold text-info text-uppercase mb-1">
                                {% translate "Total distance (km)" %}
                            </div>
                            <div class="h5 mb-0 fw-bold text-body-secondary">{{ total_distance|floatformat:2|default:0 }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="bi bi-signpost-split-fill text-body-tertiary display-5 pe-3"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl col-md-6 mb-3">
            <div class="card border border-5 border-success border-end-0 border-top-0 border-bottom-0 shadow py-2 h-100">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs fw-bold text-success text-uppercase mb-1">
                                {% translate "Spared CO<sub>2</sub> (in kg)" %}
                            </div>
                            <div class="h5 mb-0 fw-bold text-body-secondary">{{ total_co2|floatformat:2|default:0 }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="bi bi-leaf-fill text-body-tertiary display-5 pe-3"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="">
        <canvas id="chart"></canvas>
    </div>
</div>
{% endblock content %}

{% block extrascript %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    const ctx = document.getElementById('chart');

    document.addEventListener("DOMContentLoaded", function () {
        fetch("{% url 'carpool:bo_statistics_json_monthly' %}")
            .then(response => response.json())
            .then(data => {
                console.log(data);
                const labels = data.labels;
                const rideCounts = data.monthly_total_rides;
                const co2Saved = data.monthly_total_co2;
                const usersCounts = data.monthly_total_users;
                const distanceCounts = data.monthly_total_distance;

                new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: labels,
                        datasets: [
                            {
                                label: 'Rides count',
                                data: rideCounts,
                                borderWidth: 1,
                                yAxisID: 'y'
                            },
                            {
                                label: 'Spared CO2 (in kg)',
                                data: co2Saved,
                                borderWidth: 1,
                                yAxisID: 'y1'
                            },
                            {
                                label: 'Users',
                                data: usersCounts,
                                borderWidth: 1,
                                yAxisID: 'y',
                            },
                        ]
                    },
                    options: {
                        scales: {
                            // scale for number of rides
                            y: {
                                beginAtZero: true,
                                position: 'left',
                                title: {
                                    display: true,
                                }
                            },
                            // scale for CO2 saved
                            y1: {
                                beginAtZero: true,
                                position: 'right',
                                grid: {
                                    drawOnChartArea: false
                                },
                                title: {
                                    display: true,
                                    text: 'kg'
                                }
                            }
                        }
                    }
                });
            })
            .catch(error => console.error('Error fetching statistics data:', error));
    })
</script>
{% endblock extrascript %}