project/accounts/urls.py
from django.contrib.auth import views as auth_views
from accounts.views import registration as registration_views
from django.urls import path, reverse_lazy

from accounts.forms import PasswordResetForm, SetPasswordForm
from accounts.views import profile, register
from accounts.views.verify_email import (
    verify_email_complete,
    verify_email_confirm,
    verify_email_send_token,
    verify_email_sent,
)


app_name = "accounts"

urlpatterns = [
    path("login/", registration_views.CustomLoginView.as_view(), name="login"),
    path("logout/", auth_views.logout_then_login, name="logout"),
    path("register/", register, name="register"),
    path("", profile.user_profile, name="me"),
    path("delete/", profile.delete_profile, name="account_close"),
    path("email/change/", profile.email_change, name="email_change"),
    path("export/", profile.export, name="export"),
]

# Email verification URLs
urlpatterns += [
    path("register/email/", verify_email_send_token, name="verify_email_send_token"),
    path("register/email/sent/", verify_email_sent, name="verify_email_sent"),
    path(
        "register/email/confirm/<uidb64>/<token>/",
        verify_email_confirm,
        name="verify_email_confirm",
    ),
    path(
        "register/email/complete/",
        verify_email_complete,
        name="verify_email_complete",
    ),
]

# Password reset URLs
urlpatterns += [
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy("accounts:password_reset_done"),
            form_class=PasswordResetForm,
            template_name="registration/password_reset/index.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset/done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            form_class=SetPasswordForm,
            success_url=reverse_lazy("accounts:password_reset_complete"),
            template_name="registration/password_reset/index.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset/complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "password_change/",
        profile.PasswordChangeView.as_view(),
        name="password_change",
    ),
]

# forgot username
urlpatterns += [
    path(
        "forgot_username/", registration_views.forgot_username, name="forgot_username"
    ),
    path(
        "forgot_username/done/",
        registration_views.forgot_username_done,
        name="forgot_username_done",
    ),
]

project/carpool/urls.py
from django.urls import path

from carpool.views import (
    update_reservation,
    cancel_reservation,
    list_my_rides,
    rides_map,
    rides_delete,
    rides_detail,
    rides_list,
    rides_subscribe,
)
from carpool.views import api as api_views
from carpool.views import backoffice as bo_views
from carpool.views import vehicle as vehicle_views
from carpool.views import rides as rides_views
from chat.views import request_chat

app_name = "carpool"

urlpatterns = [
    path("", rides_list, name="list"),
    path("my-rides/", list_my_rides, name="my-rides"),
    path("<uuid:pk>/", rides_detail, name="detail"),
    path("<uuid:pk>/delete/", rides_delete, name="delete"),
    path("map/", rides_map, name="map"),
    path("<uuid:ride_pk>/chat/", request_chat, name="chat"),
    path("<uuid:ride_pk>/subscribe/", rides_subscribe, name="subscribe"),
]

urlpatterns += [
    path("<uuid:pk>/edit/", rides_views.edit, name="edit"),
    path("create/step1/", rides_views.create_step1, name="create_step1"),
    path("create/step2/", rides_views.create_step2, name="create_step2"),
]


# API endpoints
urlpatterns += [
    path("api/reservations/cancel/", cancel_reservation, name="cancel_reservation"),
    path("api/reservations/update/", update_reservation, name="update_reservation"),
    path("api/vehicles/new/", vehicle_views.create, name="create_vehicle"),
    path("api/vehicles/<int:pk>/update/", vehicle_views.update, name="update_vehicle"),
    path("api/completion/", api_views.autocompletion, name="completion"),
    path("api/routing/", api_views.routing, name="routing"),
]


# Back office specific URLs
urlpatterns += [
    path("back-office/statistics/", bo_views.statistics, name="bo_statistics"),
    path(
        "back-office/statistics/json/",
        bo_views.statistics_json_monthly,
        name="bo_statistics_json_monthly",
    ),
]

project/chat/urls.py
from django.urls import path

from chat.views import (
    hide_message,
    index,
    mod_center,
    mod_room,
    report,
    room,
    unhide_message,
    user_report,
)

app_name = "chat"

urlpatterns = [
    path("", index, name="index"),
    path("<uuid:jr_pk>/", room, name="room"),
    path("<uuid:jr_pk>/report/", report, name="report"),
]

urlpatterns += [
    path("mod/", mod_center, name="mod_index"),
    path("mod/<uuid:jr_pk>/", mod_room, name="mod_room"),
    path("mod/msg/<int:id>/hide/", hide_message, name="hide_message"),
    path("mod/msg/<int:id>/unhide/", unhide_message, name="unhide_message"),
    path("mod/user/<uuid:user_pk>/report/", user_report, name="user_report"),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from .views import set_user_language

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),  # language switching
    path(
        "set_language/", set_user_language, name="set_user_language"
    ),  # custom language switching
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("carpool.urls", namespace="carpool")),
    path("chat/", include("chat.urls", namespace="chat")),
]


urlpatterns += [
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/templates/includes/footer.html
{% load i18n %}<footer class="footer mt-auto py-3 px-1 bg-body-tertiary" style="z-index: 0;">
    <div class="container-fluid d-flex justify-content-end gap-3 px-3">
        <a href="{{ TERMS_OF_SERVICE }}" class="text-decoration-none">{% translate "Terms of Service" %}</a>
        <a href="{{ LEGAL_NOTICE }}" class="text-decoration-none">{% translate "Legal Notice" %}</a>
    </div>
</footer>

project/templates/includes/langselect.html
{% load i18n %}
{% get_available_languages as LANGUAGES %}
{% get_current_language as LANGUAGE_CODE %}
<form action="{% url 'set_user_language' %}" method="post">
    {% csrf_token %}
    <input name="next" type="hidden" value="{{ request.path }}">
    <select name="language" class="form-select form-select-sm" onchange="this.form.submit()">
        {% for lang in LANGUAGES %}
        <option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %}selected{% endif %}>{{ lang.1 }}</option>
        {% endfor %}
    </select>
</form>

project/templates/includes/navbar.html
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'carpool:list' %}">
            <img src="{% static 'img/logo/insa-rennes.png' %}" alt="logo INSA Rennes" class="img-fluid me-2" style="height: 30px;">
            INSA'Roule
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'list' %}active{% endif %}" 
                    {% if request.resolver_match.url_name == 'list' %}aria-current="page"{% endif %} href="{% url 'carpool:list' %}">{% translate "Rides" %}</a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'map' %}active{% endif %}" 
                    {% if request.resolver_match.url_name == 'map' %}aria-current="page"{% endif %} href="{% url 'carpool:map' %}">{% translate "Map View" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'my-rides' %}active{% endif %}" 
                    {% if request.resolver_match.url_name == 'my-rides' %}aria-current="page"{% endif %} href="{% url 'carpool:my-rides' %}">{% translate "My Rides" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.url_name == 'create' %}active{% endif %}" 
                    {% if request.resolver_match.url_name == 'create' %}aria-current="page"{% endif %} href="{% url 'carpool:create_step1' %}">{% translate "Publish a ride" %}</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}

                <li class="nav-item my-auto me-3 mb-2 my-xl-auto">
                    <a class="btn btn-sm btn-outline-primary position-relative" href="{% url 'chat:index' %}">
                        {% translate "Messages" %}
                       <!-- <span class="position-absolute top-0 start-100 translate-middle p-1 bg-danger border border-light rounded-circle">
                            <span class="visually-hidden">New alerts</span>
                        </span>-->
                    </a>
                </li>
                {% endif %}

                <div class="my-auto">
                    {% include "includes/langselect.html" %}
                </div>
                
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="{% url 'accounts:me' %}">{% translate "My Account" %}</a></li>
                        <li><a class="dropdown-item" href="mailto:{{ SUPPORT_EMAIL }}">{% translate "Report Issue" %}</a></li>
                        {% if perms.carpool.view_statistics %}
                        <li><a class="dropdown-item" href="{% url 'carpool:bo_statistics' %}">{% translate "Back Office" %}</a></li>
                        {% endif %}
                        {% if user.is_staff %}
                        <li><a class="dropdown-item text-danger fw-bold" href="{% url 'admin:index' %}">{% translate "Admin Panel" %}</a></li>
                        {% endif %}
                        {% if perms.chat.can_moderate_messages %}
                        <li>
                            <a class="dropdown-item {% if request.resolver_match.url_name == 'mod_index' %}active{% endif %}" 
                            {% if request.resolver_match.url_name == 'mod_index' %}aria-current="page"{% endif %} href="{% url 'chat:mod_index' %}">
                                {% translate "Moderation" %}
                            </a>
                        </li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <form action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <li><button type="submit" class="dropdown-item">{% translate "Logout" %}</button></li>
                        </form>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item my-auto py-xl-0 py-3 ms-xl-2 ms-0">
                    <a class="btn btn-sm btn-outline-primary" href="{% url 'accounts:login' %}">
                        {% translate "Login" %}
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>