project/carpool/urls.py
from django.urls import path

from carpool.views import (
    update_reservation,
    cancel_reservation,
    list_my_rides,
    rides_map,
    rides_delete,
    rides_detail,
    rides_list,
    rides_subscribe,
)
from carpool.views import api as api_views
from carpool.views import backoffice as bo_views
from carpool.views import vehicle as vehicle_views
from carpool.views import rides as rides_views
from chat.views import request_chat

app_name = "carpool"

urlpatterns = [
    path("", rides_list, name="list"),
    path("my-rides/", list_my_rides, name="my-rides"),
    path("<uuid:pk>/", rides_detail, name="detail"),
    path("<uuid:pk>/delete/", rides_delete, name="delete"),
    path("map/", rides_map, name="map"),
    path("<uuid:ride_pk>/chat/", request_chat, name="chat"),
    path("<uuid:ride_pk>/subscribe/", rides_subscribe, name="subscribe"),
]

urlpatterns += [
    path("<uuid:pk>/edit/", rides_views.edit, name="edit"),
    path("create/step1/", rides_views.create_step1, name="create_step1"),
    path("create/step2/", rides_views.create_step2, name="create_step2"),
]


# API endpoints
urlpatterns += [
    path("api/reservations/cancel/", cancel_reservation, name="cancel_reservation"),
    path("api/reservations/update/", update_reservation, name="update_reservation"),
    path("api/vehicles/new/", vehicle_views.create, name="create_vehicle"),
    path("api/vehicles/<int:pk>/update/", vehicle_views.update, name="update_vehicle"),
    path("api/completion/", api_views.autocompletion, name="completion"),
    path("api/routing/", api_views.routing, name="routing"),
]


# Back office specific URLs
urlpatterns += [
    path("back-office/statistics/", bo_views.statistics, name="bo_statistics"),
    path(
        "back-office/statistics/json/",
        bo_views.statistics_json_monthly,
        name="bo_statistics_json_monthly",
    ),
]

project/chat/urls.py
from django.urls import path

from chat.views import (
    hide_message,
    index,
    mod_center,
    mod_room,
    report,
    room,
    unhide_message,
    user_report,
)

app_name = "chat"

urlpatterns = [
    path("", index, name="index"),
    path("<uuid:jr_pk>/", room, name="room"),
    path("<uuid:jr_pk>/report/", report, name="report"),
]

urlpatterns += [
    path("mod/", mod_center, name="mod_index"),
    path("mod/<uuid:jr_pk>/", mod_room, name="mod_room"),
    path("mod/msg/<int:id>/hide/", hide_message, name="hide_message"),
    path("mod/msg/<int:id>/unhide/", unhide_message, name="unhide_message"),
    path("mod/user/<uuid:user_pk>/report/", user_report, name="user_report"),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from .views import set_user_language

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),  # language switching
    path(
        "set_language/", set_user_language, name="set_user_language"
    ),  # custom language switching
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("carpool.urls", namespace="carpool")),
    path("chat/", include("chat.urls", namespace="chat")),
]


urlpatterns += [
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/chat/models.py
from uuid import uuid4

from carpool.models.ride import Ride
from django.urls import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _


class ChatRequest(models.Model):
    uuid = models.UUIDField(
        verbose_name=_("UUID"),
        primary_key=True,
        editable=False,
        default=uuid4,
    )

    ride = models.ForeignKey(
        Ride,
        verbose_name=_("ride"),
        help_text=_("The ride for which the chat request is made"),
        on_delete=models.CASCADE,
        related_name="join_requests",
    )

    user = models.ForeignKey(
        "accounts.User",
        verbose_name=_("user"),
        help_text=_("The user who made the chat request"),
        related_name="join_requests",
        on_delete=models.CASCADE,
    )

    created_at = models.DateTimeField(
        verbose_name=_("created at"),
        help_text=_("The date and time when the chat request was created"),
        auto_now_add=True,
    )

    def get_room_url(self):
        return reverse("chat:room", kwargs={"jr_pk": self.pk})

    def get_mod_room_url(self):
        return reverse("chat:mod_room", kwargs={"jr_pk": self.pk})

    def __str__(self):
        return f"ChatRequest({self.user.username} for {self.ride.uuid})"


class ChatMessage(models.Model):
    content = models.TextField()
    sender = models.ForeignKey(
        "accounts.User",
        on_delete=models.CASCADE,
        related_name="chat_messages",
        verbose_name=_("sender"),
    )

    chat_request = models.ForeignKey(
        ChatRequest,
        on_delete=models.CASCADE,
        related_name="messages",
        verbose_name=_("join request"),
    )

    timestamp = models.DateTimeField(auto_now_add=True)

    hidden = models.BooleanField(
        default=False,
        verbose_name=_("hidden"),
        help_text=_("Indicates whether this message is hidden from regular users"),
    )

    read_at = models.DateTimeField(
        auto_now_add=False,
        blank=True,
        null=True,
        verbose_name=_("read at"),
        help_text=_("The date and time when the message was read"),
    )

    notified_at = models.DateTimeField(
        auto_now_add=False,
        blank=True,
        null=True,
        verbose_name=_("notified at"),
        help_text=_(
            "The date and time when the user was notified about this message (if any)"
        ),
    )

    class Meta:
        # Custom permission to moderate chat messages
        permissions = (("can_moderate_messages", _("Can moderate chat messages")),)


class ChatReport(models.Model):
    chat_request = models.ForeignKey(
        ChatRequest,
        on_delete=models.CASCADE,
        related_name="reports",
        verbose_name=_("chat request"),
    )

    reported_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.CASCADE,
        related_name="chat_reports",
        verbose_name=_("reported by"),
    )

    reason = models.TextField(verbose_name=_("reason"), blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"ChatReport({self.chat_request.uuid} by {self.reported_by.username})"


class ModAction(models.Model):
    class Action(models.TextChoices):
        FLAG_USER = "FLAG_USER", _("Flag User")  # Add a flag action
        BLOCK_USER = "BLOCK_USER", _("Block User")  # Block a user

    performed_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.CASCADE,
        related_name="mod_actions",
        verbose_name=_("performed by"),
    )

    on_user = models.ForeignKey(
        "accounts.User",
        on_delete=models.CASCADE,
        related_name="mod_actions_on_user",
        verbose_name=_("on user"),
        blank=True,
        null=True,
    )

    reason = models.TextField(
        verbose_name=_("reason"),
        help_text=_("Reason for the moderation action"),
        blank=True,
        null=True,
    )

    action = models.CharField(
        max_length=20,
        choices=Action.choices,
        verbose_name=_("action"),
        help_text=_("The type of moderation action performed"),
    )

    timestamp = models.DateTimeField(auto_now_add=True)

project/chat/views.py
import logging

from accounts.models import User
from carpool.models.reservation import Reservation
from carpool.models.ride import Ride
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator
from django.db.models import OuterRef, Q, Subquery
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext as _
from django.views.decorators.http import require_http_methods
from django.contrib.sites.shortcuts import get_current_site
from django.utils import timezone

from chat.models import ChatMessage, ChatReport, ChatRequest, ModAction
from chat.tasks import send_email_report_to_mods


@login_required
def request_chat(request, ride_pk):
    """Create a chat request for a given ride."""
    ride = get_object_or_404(Ride, pk=ride_pk)
    if request.method == "POST":
        if ChatRequest.objects.filter(user=request.user, ride=ride).exists():
            logging.warning(
                f"User {request.user} has made a chat request about ride {ride.pk}"
            )
            messages.error(
                request, _("You have already requested to chat about this ride.")
            )
            return redirect("carpool:detail", pk=ride.pk)

        chat_request = ride.join_requests.create(user=request.user)

        return redirect("chat:room", jr_pk=chat_request.pk)
    return redirect("carpool:detail", pk=ride.pk)


@login_required
def report(request, jr_pk):
    join_request = get_object_or_404(ChatRequest, pk=jr_pk)

    if request.method == "POST":
        # check if the user is a participant in the chat
        if request.user not in [join_request.user, join_request.ride.driver]:
            return HttpResponse(
                "You are not allowed to report this chat request", status=403
            )

        # Check if the user has already reported this chat request
        if ChatReport.objects.filter(
            chat_request=join_request, reported_by=request.user
        ).exists():
            messages.error(request, _("You have already reported this chat request."))
            return redirect("chat:room", jr_pk=jr_pk)

        # Handle the report submission
        ChatReport.objects.create(
            chat_request=join_request,
            reported_by=request.user,
            reason=request.POST.get("reason", ""),
        )

        # Notify moderators via email (asynchronous task)
        site_base_url = request.scheme + "://" + get_current_site(request).domain
        send_email_report_to_mods.delay(join_request.pk, site_base_url)

    messages.info(request, _("The chat request has been reported."))
    return redirect("chat:room", jr_pk=jr_pk)


@permission_required("chat.can_moderate_messages", raise_exception=True)
@require_http_methods(["POST"])
def user_report(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    join_request = get_object_or_404(
        ChatRequest,
        pk=request.POST.get("join_request_id"),
    )

    # Handle the user report submission
    ModAction.objects.create(
        performed_by=request.user,
        action=ModAction.Action.FLAG_USER,
        reason=request.POST.get("reason", ""),
        on_user=user,
    )

    return redirect("chat:mod_room", jr_pk=join_request.pk)


@permission_required("chat.can_moderate_messages", raise_exception=True)
def hide_message(request, id):
    message = get_object_or_404(ChatMessage, pk=id)
    message.hidden = True
    message.save()
    return JsonResponse({"status": "success"})


@permission_required("chat.can_moderate_messages", raise_exception=True)
def unhide_message(request, id):
    message = get_object_or_404(ChatMessage, pk=id)
    message.hidden = False
    message.save()
    return JsonResponse({"status": "success"})


@permission_required("chat.can_moderate_messages", raise_exception=True)
def mod_room(request, jr_pk):
    join_request = get_object_or_404(ChatRequest, pk=jr_pk)
    context = {"join_request": join_request}
    return render(request, "chat/moderation/room.html", context)


@permission_required("chat.can_moderate_messages", raise_exception=True)
def mod_center(request):
    query_ride = request.GET.get("ride", "")
    query_username = request.GET.get("search_by_username", "")
    query_content = request.GET.get("search_by_content", "")
    past_rides = request.GET.get("past", "")

    reports = ChatRequest.objects.all()

    if not past_rides == "1":
        reports = reports.filter(
            ride__start_dt__gte=timezone.now() - timezone.timedelta(days=1)
        )

    reports = reports.order_by("-created_at")

    if query_username:
        print(f"Searching by username: {query_username}")
        reports = reports.filter(
            Q(user__username__icontains=query_username)
            | Q(ride__driver__username__icontains=query_username)
        )
    if query_content:
        print(f"Searching by content: {query_content}")
        reports = reports.filter(Q(messages__content__icontains=query_content))

    if query_ride:
        print(f"Filtering by ride: {query_ride}")
        reports = reports.filter(ride__pk=query_ride)

    paginator = Paginator(reports, 10)  # Show 10 reports per page
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj": page_obj,
        "search_by_username": query_username,
        "search_by_content": query_content,
        "ride": query_ride,
    }
    return render(request, "chat/moderation/index.html", context)


def get_sidebar_context(request):
    """
    Get the context for the sidebar, including outgoing and incoming chat requests.
    Used to avoid code duplication in multiple views.
    """

    # Subquery to fetch the last reservation status
    last_reservation = Reservation.objects.filter(
        ride=OuterRef("ride"),
        user=OuterRef("user"),
    ).order_by("-created_at")

    outgoing_requests = (
        ChatRequest.objects.filter(user=request.user)
        .annotate(
            last_reservation_status=Subquery(last_reservation.values("status")[:1])
        )
        .order_by("ride__start_dt")
    )

    # Print last_reservation_status for debugging

    incoming_requests = (
        ChatRequest.objects.filter(ride__in=request.user.rides_as_driver.all())
        .annotate(
            last_reservation_status=Subquery(last_reservation.values("status")[:1])
        )
        .order_by("ride__start_dt")
    )

    print("Outgoing Requests with last_reservation_status:")
    for jr in outgoing_requests:
        print(
            f"JoinRequest ID: {jr.pk}, Last Reservation Status: {jr.last_reservation_status}"
        )
    print("Incoming Requests with last_reservation_status:")
    for jr in incoming_requests:
        print(
            f"JoinRequest ID: {jr.pk}, Last Reservation Status: {jr.last_reservation_status}"
        )

    # Filtering for declined (if you re-enable later)
    # if not request.GET.get("o_declined"):
    #     outgoing_requests = outgoing_requests.exclude(
    #         last_reservation_status="DECLINED"
    #     )

    # if not request.GET.get("i_declined"):
    #     incoming_requests = incoming_requests.exclude(
    #         last_reservation_status="DECLINED"
    #     )

    # Pagination
    o_paginator = Paginator(outgoing_requests, 4)
    i_paginator = Paginator(incoming_requests, 4)

    o_page_number = request.GET.get("o_page")
    i_page_number = request.GET.get("i_page")

    outgoing_requests = o_paginator.get_page(o_page_number)
    incoming_requests = i_paginator.get_page(i_page_number)

    return {
        "outgoing_requests": outgoing_requests,
        "incoming_requests": incoming_requests,
    }


@login_required
def index(request):
    context = get_sidebar_context(request)
    return render(request, "chat/index.html", context)


@login_required
def room(request, jr_pk):
    join_request = get_object_or_404(ChatRequest, pk=jr_pk)

    if request.user not in [join_request.user, join_request.ride.driver]:
        return HttpResponse("You are not allowed to access this room", status=403)

    if request.user == join_request.user:
        with_user = join_request.ride.driver
    else:
        with_user = join_request.user

    shared_ride_count = Ride.objects.count_shared_ride(request.user, with_user)

    reservation = (
        join_request.ride.reservations.filter(user=join_request.user)
        .order_by("-created_at")
        .first()
    )

    context = {
        "with_user": with_user,
        "reservation": reservation,
        "join_request": join_request,
        "shared_ride_count": shared_ride_count,
        "has_booked_ride": reservation is not None,
    }
    # Inject sidebar context
    context.update(get_sidebar_context(request))

    return render(request, "chat/room.html", context)

project/chat/templates/chat/includes/mod_profile.html
{% load static %}
{% load i18n %}
<div class="card h-100 mb-3">
    <div class="card-header">
        Moderation profile
    </div>
    <div class="card-body">
        <div class="d-flex flex-row gap-3">
            <img src="{% static 'img/avatar.jpg' %}"
                class="rounded-circle" width="70" />
            <div class="d-flex flex-column">
                <span class="fs-4">{{ profile.username }}</span>
                <span>
                    {% if jr.ride.driver == profile %}
                        <span class="badge" style="background-color: #92b389;">{% translate "Driver" %}</span>
                    {% elif jr.user == profile %}
                        <span class="badge text-dark" style="background-color: beige;">{% translate "Requester" %}</span>
                    {% else %}
                        <span class="badge bg-danger">ERROR</span>
                    {% endif %}
                </span>
            </div>
        </div>
        <div class="mt-3 text-center">
            <form action="" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-sm btn-danger disabled" name="ban_user"><i class="bi bi-ban"></i></button>
                <button type="submit" class="btn btn-sm btn-warning disabled" name="ban_user"><i class="bi bi-shield-fill-exclamation"></i></button>
            </form>
        </div>
        <div class="mt-3">
            <h5>{% translate "Report user" %}</h5>
            <form action="{% url 'chat:user_report' user_pk=profile.pk %}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <input type="hidden" name="join_request_id" value="{{ jr.pk }}">
                    <label for="reason" class="form-label">{% translate "Reason for reporting" %}</label>
                    <textarea class="form-control" id="reason" name="reason" rows="1" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary">{% translate "Report" %}</button>
            </form>



            <h5 class="mt-3">{% translate "Mod history" %}</h5>
            <ul>
                {% for report in profile.mod_actions_on_user.all %}
                <li>{{ report.timestamp|date:"SHORT_DATETIME_FORMAT" }} - {{ report.reason }}</li>
                {% empty %}
                <li class="text-muted">{% translate "No moderation actions found." %}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

project/chat/templates/chat/includes/sidebar.html
{% load i18n %} {% load duration %}
<style>
    .circle {
        width: 10px;
        height: 10px;
        border: 2px solid black;
        border-radius: 50%;
        background-color: white;
        align-self: center;
        flex-shrink: 0;
    }

    .line {
        background-color: #1b1b1b;
        flex: 1;
        border-radius: 2px;
        align-self: center;
        margin: 2px 0;
        width: 4px;
    }

    .list-group-item.active {
        --bs-list-group-active-bg: #cfe2ff;
        --bs-list-group-active-border-color: #cfe2ff;
        --bs-list-group-active-color: #084298;
    }
</style>

<div class="list-group mb-3">
    <span class="list-group-item text-bg-light">
        <div class="d-flex">
            {% translate "Ride Requests" %}
            <div class="dropdown ms-auto">
                <i class="bi bi-three-dots-vertical" data-bs-toggle="dropdown" aria-expanded="false"></i>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        {% if request.GET.o_declined %}
                        <a href="{% querystring o_declined=None %}" class="dropdown-item disabled">
                            <i class="bi bi-check-lg"></i> {% translate "Declined requests" %}
                        </a>
                        {% else %}
                        <a href="{% querystring o_declined=1 %}" class="dropdown-item disabled">
                            {% translate "Declined requests" %}
                        </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>

    </span>
    {% for jr in outgoing_requests %}
    {% include "chat/includes/sidebar_item.html" with jr=jr contact=jr.ride.driver %}
    {% empty %}
    <a href="{% url 'carpool:list' %}" class="list-group-item list-group-item-action">
        <div class="d-flex flex-column align-items-center">
            <span class="text-muted mb-2 small">
                {% translate "No ride requests found" %}
            </span>
            <span type="button" class="btn btn-sm btn-outline-primary">
                {% translate "Search a ride" %}
            </span>
        </div>
    </a>
    {% endfor %}
</div>

{# Pagination for outgoing requests #}
{% if outgoing_requests.has_other_pages %}
<nav>
    <ul class="pagination pagination-sm my-3 justify-content-center">
        <li class="page-item"><a class="page-link {% if not outgoing_requests.has_previous %}disabled{% endif %}"
                href="{% querystring o_page=1 %}">&laquo;</a></li>
        <li class="page-item"><a class="page-link {% if not outgoing_requests.has_previous %}disabled{% endif %}"
                href="{%if outgoing_requests.has_previous%}{%querystring o_page=outgoing_requests.previous_page_number%}{%endif%}">&lsaquo;</a>
        </li>
        <li class="page-item"><span class="page-link text-dark">{{ outgoing_requests.number }} / {{ outgoing_requests.paginator.num_pages }}</span></li>
        
        <li class="page-item"><a class="page-link {% if not outgoing_requests.has_next %}disabled{% endif %}"
                href="{%if outgoing_requests.has_next%}{%querystring o_page=outgoing_requests.next_page_number%}{%endif%}">&rsaquo;</a>
        </li>
        <li class="page-item"><a class="page-link {% if not outgoing_requests.has_next %}disabled{% endif %}"
                href="{% querystring o_page=outgoing_requests.paginator.num_pages %}">&raquo;</a></li>
    </ul>
</nav>
{% endif %}

<div class="list-group">
    <span class="list-group-item text-bg-light">
        <div class="d-flex">
            {% translate "Incoming requests" %}
            <div class="dropdown ms-auto">
                <i class="bi bi-three-dots-vertical" data-bs-toggle="dropdown" aria-expanded="false"></i>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        {% if request.GET.i_declined %}
                        <a href="{% querystring i_declined=None %}" class="dropdown-item disabled">
                            <i class="bi bi-check-lg"></i> {% translate "Declined requests" %}
                        </a>
                        {% else %}
                        <a href="{% querystring i_declined=1 %}" class="dropdown-item disabled">
                            {% translate "Declined requests" %}
                        </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </span>
    {% for jr in incoming_requests %}
    {% include "chat/includes/sidebar_item.html" with jr=jr contact=jr.user %}

    {% empty %}

    <span class="list-group-item text-muted text-center small">
        {% translate "Nobody has requested to join your rides yet." %}
    </span>

    {% endfor %}
</div>

{# Pagination for incoming requests #}
{% if incoming_requests.has_other_pages %}
<nav>
    <ul class="pagination pagination-sm my-3 justify-content-center">
        <li class="page-item"><a class="page-link {% if not incoming_requests.has_previous %}disabled{% endif %}"
                href="{% querystring i_page=1 %}">&laquo;</a></li>
        <li class="page-item"><a class="page-link {% if not incoming_requests.has_previous %}disabled{% endif %}"
                href="{%if incoming_requests.has_previous%}{%querystring i_page=incoming_requests.previous_page_number%}{%endif%}">&lsaquo;</a>
        </li>
        <li class="page-item"><span class="page-link text-dark">{{ incoming_requests.number }} / {{ incoming_requests.paginator.num_pages }}</span></li>
        
        <li class="page-item"><a class="page-link {% if not incoming_requests.has_next %}disabled{% endif %}"
                href="{%if incoming_requests.has_next%}{%querystring i_page=incoming_requests.next_page_number%}{%endif%}">&rsaquo;</a>
        </li>
        <li class="page-item"><a class="page-link {% if not incoming_requests.has_next %}disabled{% endif %}"
                href="{% querystring i_page=incoming_requests.paginator.num_pages %}">&raquo;</a></li>
    </ul>
</nav>
{% endif %}

project/chat/templates/chat/includes/sidebar_item.html
{% url 'chat:room' jr.pk as jr_url %}
<a href="{{ jr_url }}{% querystring %}"
    class="list-group-item list-group-item-action {% if request.path == jr_url %}active{% endif %}">
    <div class="d-flex justify-content-between">
        <div class="d-grid">
            <div class="d-flex flex-row">
                <div class="d-flex flex-column mx-1 my-1">
                    <div class="circle"></div>
                    <div class="line"></div>
                    <div class="circle"></div>
                </div>
                <div class="d-flex flex-column ms-2">
                    <span>{{ jr.ride.start_loc.city|truncatechars:20 }}</span>
                    <span class="h-100"></span>
                    <span>{{ jr.ride.end_loc.city|truncatechars:20 }}</span>
                </div>
            </div>
        </div>
        <div class="d-flex flex-column align-items-end">
            <span>{{ jr.ride.start_dt|date:"d/m/Y" }}</span>
            <span>
                <span>{{ contact.username|truncatechars:16 }}</span>
                {% if jr.last_reservation_status == "PENDING" %}
                <span>
                    <i class="bi bi-envelope-fill"></i>
                </span>
                {% elif jr.last_reservation_status == "ACCEPTED" %}
                <span class="text-success">
                    <i class="bi bi-envelope-check-fill"></i>
                </span>
                {% elif jr.last_reservation_status == "DECLINED" %}
                <span class="text-danger">
                    <i class="bi bi-envelope-x-fill"></i>
                </span>
                {% elif jr.last_reservation_status == "CANCELED" %}
                <span class="text-warning">
                    <i class="bi bi-envelope-x-fill"></i>
                </span>
                {% endif %}
            </span>
        </div>
    </div>
</a>